### ISSUE TITLE
local-481 broken?

### ISSUE THREAD

**Issue by fahrenhe1t** [NathanVaughn/powerpanel-business-docker#14]
I have a docker-compose.yml that works with powerpanel-business:local-470.  However powerpanel-business:local-481 will not load with the same docker-compose.yml 

```
HTTP Status 404 – Not Found
Type Status Report
Message /local/login
Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.
```
```
version: '3'

services:
  powerpanel:
    image: ghcr.io/nathanvaughn/powerpanel-business:local-481
    hostname: powerpanel
    container_name: powerpanel
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
    ports:
      - 2003:2003 # Powerpanel Watchdog Service
      - 3052:3052 # http
      - 53566:53566/udp # unknown
    devices:
      - "/dev/usb:/dev/usb"
    #privileged: true
    restart: unless-stopped
    volumes:
      - app_data:/usr/local/ppbe/db_local/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
volumes:
  app_data:
    driver: local
```
