### ISSUE TITLE
404 with Traefik

### ISSUE THREAD

**Issue by mattsnowboard** [NathanVaughn/powerpanel-business-docker#32]
I use Traefik as a reverse proxy and couldn't get this working yet.

Here are the hopefully relevant parts of my docker compose file:

```yml
version: "3.9"

networks:
  default:
    driver: bridge
  t2_proxy:
    name: t2_proxy
    driver: bridge
    ipam:
      config:
        - subnet: $T2_PROXY_SUBNET

volumes:
  powerpanel_app_data:
    driver: local

services:
  # UPS
  powerpanel:
    image: ghcr.io/nathanvaughn/powerpanel-business:both-latest
    container_name: powerpanel
    networks:
      - t2_proxy
    # build: .
    ports:
      # Ports: ???, http, https, ???, snmp, snmp
      # See https://dl4jz3rbrsfum.cloudfront.net/documents/CyberPower_UM_PowerPanel-Business-490.pdf
      - 2003:2003
      - 3052:3052 # HTTP access, see traefik settings below
      - 53568:53568/tcp # HTTPS access
      - 53566:53566/udp
      - 161:161/udp
      - 162:162/udp
    devices:
      # sharing /dev/usb is sufficient for debian and ubuntu,
      # but other distributions might also need access to
      # /dev/bus/usb/*
      - "/dev/usb:/dev/usb"
      # - "/dev/bus/usb:/dev/bus/usb"
    restart: unless-stopped
    volumes:
      - powerpanel_app_data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.powerpanel-rtr.entrypoints=https"
      - "traefik.http.routers.powerpanel-rtr.rule=Host(`ups.$DOMAINNAME`)"
      ## Middlewares
      - "traefik.http.routers.powerpanel-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.powerpanel-rtr.middlewares=powerpanelHeaders@file"
      ## HTTP Services
      - "traefik.http.routers.powerpanel-rtr.service=powerpanel-svc"
      - "traefik.http.services.powerpanel-svc.loadbalancer.server.port=3052"
```

Traefik middleware to set origin (hopefully):

```
File Edit Options Buffers Tools Help
http:
  middlewares:
    powerpanelHeaders:
      headers:
        customRequestHeaders:
          Origin: ""
```

But when I visit "https://ups.MYDOMAIN" I get redirected to https://ups.MYDOMAIN/local and get a 404 response. Hopefully I'm just missing something simple
